apiVersion: shipa.crossplane.io/v1alpha1
kind: AppEnv
metadata:
  name: booking-service-env
spec:
  forProvider:
    app: booking-service
    app_env:
      envs:
        - name: DB_SERVER
          value: xx.xx.xx.xx:27017
        - name: DB_USER
          value: shipau
        - name: DB_PASS
          value: shipapass
        - name: DB
          value: booking
        - name: NOTIFICATION_API_HOST
          value: 
        - name: PAYMENT_API_HOST
          value: 
      norestart: true
      private: true
