apiVersion: shipa.crossplane.io/v1alpha1
kind: AppDeploy
metadata:
  name: catalog-service-deploy
spec:
  forProvider:
    app: catalog-service
    image: "gcr.io/cosimages-206514/cinema-catalog-service@sha256:6613440a460e9f1e6e75ec91d8686c1aa11844b3e7c5413e241c807ce9829498"
